# https://hub.docker.com/_/nginx
FROM nginx
# A directory where the result of executing envsubst is output
# ./default.conf.template will be output with the filename /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf