# https://docs.docker.com/build/ci/github-actions/#get-started-with-github-actions
name: Builds and pushes to the Docker Hub repository CI
run-name: Push Docker image to Docker Hub.
on:
  push:
    branches: ["main"]

env:
  LATEST_TAG: latest
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository on the build machine.
      - name: Check out the repo
        uses: actions/checkout@v4

      # Signs in to Docker Hub, using the Docker Login action and your Docker Hub credentials.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Creates a BuildKit builder instance using the Docker Setup Buildx action.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Builds production version of all projects and pushes it to the Docker Hub repository.

      - name: Build and push docker frontend image.
        uses: docker/build-push-action@v5
        with:
          # the build context.
          context: frontend/
          # filepath to the Dockerfile.
          file:
            frontend/Dockerfile
            # tells the action to upload the image to a registry after building it
          push: true
          # tags that specify where to push the image.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kube-multi-container-frontend:${{env.LATEST_TAG}}

      - name: Build and push docker backend image
        uses: docker/build-push-action@v5
        with:
          context: backend/
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kube-multi-container-backend:${{env.LATEST_TAG}}

      - name: Build and push Docker worker image
        uses: docker/build-push-action@v5
        with:
          context: worker/
          file: worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kube-multi-container-worker:${{env.LATEST_TAG}}
